<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Repositories\ISharedRepository;
use Illuminate\Http\Request;
use App\Model\Goals;
use Auth;
use Illuminate\Support\Collection;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Http;

class SharedController extends Controller {
    
    public function __construct(ISharedRepository $repository)
    {
        parent::__construct();
        $this->repository = $repository;
        $this->middleware('auth');
        
    }


    public function index(Request $request){
       
  
 
       /*  $response = Http::post('https://staging.athenabasketball.com/api/login', [
            'email'=>'echedli1@gmail.com',
            'password'=>'099668210'
        ]);
        dd($response->getBody()->getContents());
    	$statusCode = $response->getStatusCode();
    	$body = $response->getBody()->getContents();
         */

       /*  $user = Auth::user();
        //dd($user);
         // Get Videos of the week by product
        $planVideos = $this->repository->GetallVideosOfWeek($user);

    	return view('shared.info',[
            'sharedVideos'=> $planVideos
        ]); */

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$data = array (
        'TransactionType' => 'PreAuthorization',
        'Amount' => 100,
        'Currency' => '352',
        'TransactionDate' => '2021-07-06T00:23:30.708Z',
        'OrderId' => 'INTEGR421602',
        'PaymentMethod' => 
        array (
          'PaymentType' => 'Card',
          'PAN' => '5587402000012037',
          'ExpYear' => '2022',
          'ExpMonth' => '09',
        ),
        'Metadata' => 
        array (
          'Payload' => 'TESTING',
        ),
    );

//dd(json_encode($data));
curl_setopt($ch, CURLOPT_URL, 'https://test.borgun.is/rpg/api/payment');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
curl_setopt($ch, CURLOPT_USERPWD, '891451_puZw2H22X7Wcf5ErHxDmOmr1XlnlG6OhZn' . ':' . '');

$headers = array();
$headers[] = 'Content-Type: application/json; charset=utf-8';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
//dd($result);
dd(curl_getinfo($ch, CURLINFO_HTTP_CODE));
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);



        return \view('subscription.borgun');
    }
}
